### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by pjaclark** [TI-Tokyo/riak-java-client#3]
Create 2.2.0 docs using Maven with JavaDoc plugin.

**Comment by daniel020403** [comment]
PR for Mava javadoc plugin adjustment: https://github.com/TI-Tokyo/riak-java-client/pull/4

**Comment by daniel020403** [comment]
PR for github pages for 2.1.2 snapshot API documentation: https://github.com/TI-Tokyo/riak-java-client/pull/5

**Comment by daniel020403** [comment]
@pjaclark @Bob-The-Marauder , I think we can close this issue. This has been included in this PR: https://github.com/TI-Tokyo/riak-docs-fork/pull/53
